// Autogenerated Scheme to C++ Code
// File: Example1.cpp
#include <iostream>
#include "Object.h"
using namespace std;


Object average (Object a, Object b)
{
	Object __RetVal;
	__RetVal = b;
	__RetVal = ((a + b) / Object(2));
	return __RetVal;
}

int main ()
{
	Object __RetVal;
	cout << Object("The average of -7 and 5 is ");
;
	cout << average(Object(-7), Object(5));
;
	cout << endl;
;
	return 0;
}
