// Autogenerated Scheme to C++ Code
// File: Example5.cpp
#include <iostream>
#include "Object.h"
using namespace std;


Object test (Object a, Object b)
{
	Object __RetVal;
	cout << a;
;
	cout << Object(" < ");
;
	cout << b;
;
	cout << Object(" : ");
;
	if ((a < b))
	{
		__RetVal = Object("#t");
	}
	else
	{
		__RetVal = Object("#f");
	}
;
	return __RetVal;
}

int main ()
{
	Object __RetVal;
	cout << test(Object(7), Object(-5));
;
	cout << endl;
;
	cout << test(Object(rational(3,4)), Object(rational(4,5)));
;
	cout << endl;
;
	return 0;
}
