// Autogenerated Scheme to C++ Code
// File: Example4.cpp
#include <iostream>
#include "Object.h"
using namespace std;


int main ()
{
	Object __RetVal;
	cout << Object("The sum of 1/2, 5/3, and  6/7 is ");
;
	cout << ((Object(rational(1,2)) + Object(rational(5,3))) + Object(rational(6,7)));
;
	cout << endl;
;
	return 0;
}
