// Autogenerated Scheme to C++ Code
// File: Example3.cpp
#include <iostream>
#include "Object.h"
using namespace std;


Object sum (Object L)
{
	Object __RetVal;
	if (nullp (L))
	{
		__RetVal = Object(0);
	}
	else
	{
		__RetVal = (listop ("car", L) + sum(listop ("cdr", L)));
	}
;
	return __RetVal;
}

Object count (Object L)
{
	Object __RetVal;
	if (nullp (L))
	{
		__RetVal = Object(0);
	}
	else
	{
		__RetVal = (Object(1) + count(listop ("cdr", L)));
	}
;
	return __RetVal;
}

Object average (Object L)
{
	Object __RetVal;
	{
		Object total = sum(L);
		Object num = count(L);
		if ((Object(0) == num))
		{
			__RetVal = Object("Average cannot be calculated");
		}
		else
		{
			__RetVal = (total / num);
		}
;
	}
;
	return __RetVal;
}

int main ()
{
	Object __RetVal;
	cout << Object("The average of '(1 5 6) is ");
;
	cout << average(Object("(1 5 6 )"));
;
	cout << endl;
;
	cout << Object("The average of '() is ");
;
	cout << average(Object("()"));
;
	cout << endl;
;
	cout << Object("The average of '(5 -1 3 7 10) is ");
;
	cout << average(Object("(5 -1 3 7 10 )"));
;
	cout << endl;
;
	return 0;
}
