// Autogenerated Scheme to C++ Code
// File: Example7.cpp
#include <iostream>
#include "Object.h"
using namespace std;


int main ()
{
	Object __RetVal;
	if ((Object("#t") && ! (Object("#f"))))
	{
		cout << Object("(#t and (not #f ) )");
;
	}
	else
	{
		cout << endl;
;
	}
;
	return 0;
}
