// Autogenerated Scheme to C++ Code
// File: Example6.cpp
#include <iostream>
#include "Object.h"
using namespace std;


Object average (Object a, Object b)
{
	Object __RetVal;
	__RetVal = b;
	__RetVal = ((a + b) / Object(2));
	return __RetVal;
}

int main ()
{
	Object __RetVal;
	cout << Object("The average of -7/4 and 5/3 is ");
;
	cout << average(Object(rational(-7,4)), Object(rational(5,3)));
;
	cout << endl;
;
	return 0;
}
