submit : Object.cpp Object.h README.txt
	rm -rf BerlinMP3
	mkdir BerlinMP3
	cp Object.cpp BerlinMP3
	cp Object.h BerlinMP3
	cp README.txt BerlinMP3
	tar cfvz BerlinMP3.tgz BerlinMP3
	cp BerlinMP3.tgz ~tiawatts/cs460drop